select
    id as player_id,
    team as team_id,
    web_name,
    first_name,
    second_name,
    total_points,
    points_per_game,
    bonus as total_bonus,
    now_cost,
    status,
    goals_scored as total_goals_scored,
    assists as total_assists,
    goals_conceded as total_goals_conceded,
    own_goals as total_own_goals,
    minutes as total_minutes,
    case element_type
        when 1 then 'GKP'
        when 2 then 'DEF'
        when 3 then 'MID'
        when 4 then 'FWD'
    end as position,
    penalties_missed as total_penalties,
    starts as total_starts,
    starts_per_90,
    saves_per_90,
    goals_conceded_per_90,
    cast(expected_goals as float) as total_expected_goals,
    cast(expected_assists as float) as total_expected_assists,
    cast(expected_goal_involvements as float) as total_expected_goal_involvements,
    cast(expected_goals_conceded as float) as total_expected_goals_conceded,
    expected_goal_involvements_per_90,
    expected_goals_per_90,
    expected_assists_per_90,
    expected_goals_conceded_per_90,
    clean_sheets as total_clean_sheets,
    clean_sheets_per_90,
    penalties_saved as total_penalties_saved,
    penalties_order,
    corners_and_indirect_freekicks_order,
    direct_freekicks_order,
    transfers_in,
    transfers_out,
    yellow_cards as total_yellow_cards,
    red_cards as total_red_cards,
    selected_by_percent as overall_selected_by_percent,
    selected_rank as overall_selected_rank,
    in_dreamteam,
    dreamteam_count,
    news,
    form,
    cast(ict_index as float) as overall_ict_index,
    cast(influence as float) as overall_influence,
    cast(creativity as float) as overall_creativity,
    cast(threat as float) as overall_threat,
    points_per_game_rank,
    now_cost_rank,
    form_rank,
    ict_index_rank,
    influence_rank,
    creativity_rank,
    threat_rank
from
    {{ source('fantasypl_raw', 'players') }}