select
    element as player_id,
    round as gameweek_id,
    fixture as fixture_id,
    opponent_team as opponent_team_id,
    team_h_score as home_team_score,
    team_a_score as away_team_score,
    total_points,
    bonus,
    value,
    goals_scored,
    assists,
    goals_conceded,
    clean_sheets,
    own_goals,
    penalties_missed,
    saves,
    penalties_saved,
    expected_goal_involvements,
    expected_goals,
    expected_assists,
    expected_goals_conceded,
    was_home,
    starts,
    minutes,
    yellow_cards,
    red_cards,
    kickoff_time,
    bps,
    transfers_in,
    transfers_out,
    transfers_balance,
    selected,
    influence,
    creativity,
    threat,
    ict_index
from
    {{ source('fantasypl_raw', 'player_stats') }}