select
    id as player_id,
    team as team_id,
    web_name,
    first_name,
    second_name,
    total_points,
    points_per_game,
    bonus,
    now_cost,
    status,
    goals_scored,
    assists,
    goals_conceded,
    own_goals,
    minutes,
    case element_type
        when 1 then 'GKP'
        when 2 then 'DEF'
        when 3 then 'MID'
        when 4 then 'FWD'
    end as position,
    penalties_missed,
    starts,
    starts_per_90,
    saves_per_90,
    goals_conceded_per_90,
    expected_goals,
    expected_assists,
    expected_goal_involvements,
    expected_goals_conceded,
    expected_goal_involvements_per_90,
    expected_goals_per_90,
    expected_assists_per_90,
    expected_goals_conceded_per_90,
    clean_sheets,
    clean_sheets_per_90,
    penalties_saved,
    penalties_order,
    corners_and_indirect_freekicks_order,
    direct_freekicks_order,
    transfers_in,
    transfers_out,
    yellow_cards,
    red_cards,
    selected_by_percent,
    selected_rank,
    in_dreamteam,
    dreamteam_count,
    news,
    form,
    ict_index,
    influence,
    creativity,
    threat,
    points_per_game_rank,
    now_cost_rank,
    form_rank,
    ict_index_rank,
    influence_rank,
    creativity_rank,
    threat_rank
from
    {{ source('fantasypl_raw', 'players') }}