
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python FPL Extract Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  id-token: write

env:
  ROLE_TO_ASSUME: arn:aws:iam::017757760939:role/role-gh-actions-fpl
  ROLE_SESSION_NAME: GitHub_to_AWS_via_FederatedOIDC
  AWS_REGION: ap-southeast-2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/workflows/pytest_requirements.txt
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{env.ROLE_TO_ASSUME}}
        role-session-name: ${{env.ROLE_SESSION_NAME}}
        aws-region: ${{env.AWS_REGION}}
    - name: Test with pytest
      run: |
        pytest
